[package]
name = "lorentz"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "1.0.0"
piston2d-graphics = "0.44.0"
pistoncore-glutin_window = "0.72.0"
piston2d-opengl_graphics = "0.85.0"
tinyaudio = "*"
crossbeam = "0.8.4"
clap = "4.5.16"
anyhow = "1.0.86"
thread-priority = "1.1.0"
